//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaRepacker.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaRepacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap _8800000_attack_10 {
            get {
                object obj = ResourceManager.GetObject("_8800000_attack_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Your browser or image viewer is too OLD to view this image. Please download a newer browser such as Firefox.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AnimCompatMessage {
            get {
                return ResourceManager.GetString("AnimCompatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error at animation builder, frame {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AnimError {
            get {
                return ResourceManager.GetString("AnimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animated Portable Network Graphics (*.png)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApngFilter {
            get {
                return ResourceManager.GetString("ApngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap cog {
            get {
                object obj = ResourceManager.GetObject("cog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap copyFile {
            get {
                object obj = ResourceManager.GetObject("copyFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Foothold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditFoothold {
            get {
                return ResourceManager.GetString("EditFoothold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditPortal {
            get {
                return ResourceManager.GetString("EditPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mob spawnpoint과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditSP {
            get {
                return ResourceManager.GetString("EditSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use custom encryption key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EncTypeCustom {
            get {
                return ResourceManager.GetString("EncTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bruteforce AES key (Generate)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EncTypeGenerate {
            get {
                return ResourceManager.GetString("EncTypeGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GMS (old)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EncTypeGMS {
            get {
                return ResourceManager.GetString("EncTypeGMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MSEA / EMS / Taiwan / 메이플스토리 (old)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EncTypeMSEA {
            get {
                return ResourceManager.GetString("EncTypeMSEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BMS / GMS / MapleSEA / メイプルストーリー / 메이플스토리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EncTypeNone {
            get {
                return ResourceManager.GetString("EncTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter valid input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterValidInput {
            get {
                return ResourceManager.GetString("EnterValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter valid input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterValidInput1 {
            get {
                return ResourceManager.GetString("EnterValidInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is only available under the x86 version of HaRepacker, please get the alternative version.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExecutingAssemblyError {
            get {
                return ResourceManager.GetString("ExecutingAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Input was invalid.
        ///Please provide valid values before confirming.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FHMapperInvalidInput {
            get {
                return ResourceManager.GetString("FHMapperInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   force value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FHSettingsForceValue {
            get {
                return ResourceManager.GetString("FHSettingsForceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} was invalid.
        ///Please make sure all values are valid before confirming.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FHSettingsInvalidMessage {
            get {
                return ResourceManager.GetString("FHSettingsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   next value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FHSettingsNextValue {
            get {
                return ResourceManager.GetString("FHSettingsNextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   portal type value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FHSettingsPortalValue {
            get {
                return ResourceManager.GetString("FHSettingsPortalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   prev value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FHSettingsPrevValue {
            get {
                return ResourceManager.GetString("FHSettingsPrevValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FHSettingsXValue {
            get {
                return ResourceManager.GetString("FHSettingsXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FHSettingsYValue {
            get {
                return ResourceManager.GetString("FHSettingsYValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap folder_add {
            get {
                object obj = ResourceManager.GetObject("folder_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap folder_go {
            get {
                object obj = ResourceManager.GetObject("folder_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Images (*.jpg;*.bmp;*.png;*.gif;*.tiff)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImagesFilter {
            get {
                return ResourceManager.GetString("ImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap img_default {
            get {
                object obj = ResourceManager.GetObject("img_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Select the WZ encryption used:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InteractionWzMapleVersionInfo {
            get {
                return ResourceManager.GetString("InteractionWzMapleVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WZ Encryption과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InteractionWzMapleVersionTitle {
            get {
                return ResourceManager.GetString("InteractionWzMapleVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ladyboss_test_attack2_0 {
            get {
                object obj = ResourceManager.GetObject("ladyboss_test_attack2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap lightning {
            get {
                object obj = ResourceManager.GetObject("lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Add canvas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddCanvas {
            get {
                return ResourceManager.GetString("MainAddCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add convex과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddConvex {
            get {
                return ResourceManager.GetString("MainAddConvex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add directory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddDir {
            get {
                return ResourceManager.GetString("MainAddDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add double과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddDouble {
            get {
                return ResourceManager.GetString("MainAddDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add float과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddFloat {
            get {
                return ResourceManager.GetString("MainAddFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddImg {
            get {
                return ResourceManager.GetString("MainAddImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add int과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddInt {
            get {
                return ResourceManager.GetString("MainAddInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portal Type: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAdditionalInfo_PortalType {
            get {
                return ResourceManager.GetString("MainAdditionalInfo_PortalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add link과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddLink {
            get {
                return ResourceManager.GetString("MainAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add null과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddNull {
            get {
                return ResourceManager.GetString("MainAddNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add short과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddShort {
            get {
                return ResourceManager.GetString("MainAddShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add sound과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddSound {
            get {
                return ResourceManager.GetString("MainAddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add string과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddString {
            get {
                return ResourceManager.GetString("MainAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add sub과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddSub {
            get {
                return ResourceManager.GetString("MainAddSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Tab과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddTabTitle {
            get {
                return ResourceManager.GetString("MainAddTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add vector과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainAddVec {
            get {
                return ResourceManager.GetString("MainAddVec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot insert selected object into this type of wz node.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainCannotInsertToNode {
            get {
                return ResourceManager.GetString("MainCannotInsertToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to abort the current operation?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainConfirmAbort {
            get {
                return ResourceManager.GetString("MainConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy WZ nodes to clipboard? (warning - can take a lot of time if many nodes are selected)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainConfirmCopy {
            get {
                return ResourceManager.GetString("MainConfirmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to exit?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainConfirmExit {
            get {
                return ResourceManager.GetString("MainConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste WZ nodes from clipboard? (warning - can take a lot of time if many nodes are pasted)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainConfirmPaste {
            get {
                return ResourceManager.GetString("MainConfirmPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove this node?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainConfirmRemove {
            get {
                return ResourceManager.GetString("MainConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove this node?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainConfirmRemoveNode {
            get {
                return ResourceManager.GetString("MainConfirmRemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainConfirmRename {
            get {
                return ResourceManager.GetString("MainConfirmRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not convert &quot;{0}&quot; to the required type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainConversionError {
            get {
                return ResourceManager.GetString("MainConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t copy directories because they require too much memory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainCopyDirError {
            get {
                return ResourceManager.GetString("MainCopyDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open WZ file &quot;{0}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainCouldntOpenWZ {
            get {
                return ResourceManager.GetString("MainCouldntOpenWZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error importing {0}.img file. Are you sure you have selected the correct WZ encryption?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainErrorImportingWzImageFile {
            get {
                return ResourceManager.GetString("MainErrorImportingWzImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to open/save to the specified file path. Please run as an Administrator instead.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainFileOpenFail {
            get {
                return ResourceManager.GetString("MainFileOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help could not be shown because the help file ({0}) was not found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainHelpOpenFail {
            get {
                return ResourceManager.GetString("MainHelpOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not load image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainImageLoadError {
            get {
                return ResourceManager.GetString("MainImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &quot;{0}&quot; is invalid and will be skipped. Error: {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainInvalidFileError {
            get {
                return ResourceManager.GetString("MainInvalidFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file at {0} is a List.wz file and will be skipped.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainListWzDetected {
            get {
                return ResourceManager.GetString("MainListWzDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A node with that name already exists. Please choose a different name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainNodeExists {
            get {
                return ResourceManager.GetString("MainNodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to reload all files?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainReloadAll {
            get {
                return ResourceManager.GetString("MainReloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the WZ file to save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainSelectWzFolder {
            get {
                return ResourceManager.GetString("MainSelectWzFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t find a parent WzFile to add this WzDirectoryProperty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTreeAddDirError {
            get {
                return ResourceManager.GetString("MainTreeAddDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reached the end of the tree과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTreeEnd {
            get {
                return ResourceManager.GetString("MainTreeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to unload all files?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainUnloadAll {
            get {
                return ResourceManager.GetString("MainUnloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///
        ///Click &quot;Yes&quot; to download the new version.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainUpdateAvailable {
            get {
                return ResourceManager.GetString("MainUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainUpdateTitle {
            get {
                return ResourceManager.GetString("MainUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export directory not found. Please specify it under Tools -&gt; Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainWzExportError {
            get {
                return ResourceManager.GetString("MainWzExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to include the base64 data of image, mp3 &amp; other binary data in the json?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainWzExportJson_IncludeBase64 {
            get {
                return ResourceManager.GetString("MainWzExportJson_IncludeBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainWzExportJson_IncludeBase64_Title {
            get {
                return ResourceManager.GetString("MainWzExportJson_IncludeBase64_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   MPEG-1 Audio Layer 3 (*.mp3)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Mp3Filter {
            get {
                return ResourceManager.GetString("Mp3Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indent must be above 0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OptionsIndentError {
            get {
                return ResourceManager.GetString("OptionsIndentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap orangeMushroom_Jump {
            get {
                object obj = ResourceManager.GetObject("orangeMushroom_Jump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap orangeMushroom_Stand {
            get {
                object obj = ResourceManager.GetObject("orangeMushroom_Stand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap page_add {
            get {
                object obj = ResourceManager.GetObject("page_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap page_edit {
            get {
                object obj = ResourceManager.GetObject("page_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap page_go {
            get {
                object obj = ResourceManager.GetObject("page_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap pasteFile {
            get {
                object obj = ResourceManager.GetObject("pasteFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Pause_ {
            get {
                object obj = ResourceManager.GetObject("Pause_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap play_ {
            get {
                object obj = ResourceManager.GetObject("play_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap red_x1 {
            get {
                object obj = ResourceManager.GetObject("red_x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {0} day(s) ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RelativeTime_DaysAgo {
            get {
                return ResourceManager.GetString("RelativeTime_DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} hour(s) ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RelativeTime_HoursAgo {
            get {
                return ResourceManager.GetString("RelativeTime_HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} minute(s) ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RelativeTime_MinutesAgo {
            get {
                return ResourceManager.GetString("RelativeTime_MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} month(s) ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RelativeTime_MonthsAgo {
            get {
                return ResourceManager.GetString("RelativeTime_MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} second(s) ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RelativeTime_SecondsAgo {
            get {
                return ResourceManager.GetString("RelativeTime_SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} years(s) ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RelativeTime_YearsAgo {
            get {
                return ResourceManager.GetString("RelativeTime_YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   The node &quot;{0}&quot; already exists. Do you want it to be replaced?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceConfirm {
            get {
                return ResourceManager.GetString("ReplaceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version must be above 0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveVersionError {
            get {
                return ResourceManager.GetString("SaveVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select default XML folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectDefaultXmlFolder {
            get {
                return ResourceManager.GetString("SelectDefaultXmlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selection Type: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectionType {
            get {
                return ResourceManager.GetString("SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select MP3 File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectMp3 {
            get {
                return ResourceManager.GetString("SelectMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select where to save the animation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectOutApng {
            get {
                return ResourceManager.GetString("SelectOutApng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the output directory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectOutDir {
            get {
                return ResourceManager.GetString("SelectOutDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select where to save the file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectOutWz {
            get {
                return ResourceManager.GetString("SelectOutWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select where to save the XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectOutXml {
            get {
                return ResourceManager.GetString("SelectOutXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the WZ File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectWz {
            get {
                return ResourceManager.GetString("SelectWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the IMG files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectWzImg {
            get {
                return ResourceManager.GetString("SelectWzImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the XML files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectXml {
            get {
                return ResourceManager.GetString("SelectXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap sort {
            get {
                object obj = ResourceManager.GetObject("sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Subpanel_Loading {
            get {
                return ResourceManager.GetString("Subpanel_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WZ File (*.wz)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WzFilter {
            get {
                return ResourceManager.GetString("WzFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WZ Image Files (*.img)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WzImgFilter {
            get {
                return ResourceManager.GetString("WzImgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   eXtended Markup Language (*.xml)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string XmlFilter {
            get {
                return ResourceManager.GetString("XmlFilter", resourceCulture);
            }
        }
    }
}
